# Generated by Django 4.1.5 on 2023-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Cat", models.CharField(max_length=50)),
                ("Users", models.IntegerField()),
                ("Rating", models.IntegerField()),
                ("Reviews", models.TextField()),
            ],
        ),
    ]
