# Generated by Django 4.1.5 on 2023-06-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game", name="Rating", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="game", name="Users", field=models.CharField(max_length=50),
        ),
    ]
