# Generated by Django 4.1.5 on 2023-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cloths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Price", models.IntegerField()),
                ("Cat", models.CharField(max_length=50)),
                ("Brand", models.CharField(max_length=50)),
                ("Size", models.IntegerField()),
            ],
        ),
    ]
